<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Income_OSB_Application/AgentSB/validateAgentByUserId" name="validateAgentByUserId_db-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="validateAgentByUserId.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Income_OSB_Application/AgentSB/validateAgentByUserId"/>
    <wsdl:binding name="validateAgentByUserId_ptt-binding" type="val:validateAgentByUserId_ptt" xmlns:val="http://xmlns.oracle.com/pcbpel/adapter/db/Income_OSB_Application/AgentSB/validateAgentByUserId">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="validateAgentByUserIdSelect">
            <soap:operation soapAction="validateAgentByUserIdSelect"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>